import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Sidebar que se genera automáticamente a partir de la estructura de carpetas
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Sidebar manualmente definido
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
  */
  myCustomSidebar: [
    {
      type: 'category',
      label: 'Suerte Ganadora',
      items: ['suerte-ganadora/notion suerte ganadora'],
    },
  ],
};

export default sidebars;
