import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  projectsSidebar: [{type: 'autogenerated', dirName: 'projects'}],
  infrastructureSidebar: [{type: 'autogenerated', dirName: 'infrastructure'}],
};

export default sidebars;
