import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {

  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

   myCustomSidebar: [
    {
      type: 'category',
      label: 'Suerte Ganadora',
      items: ['suerte-ganadora/notion_suerte_ganadora'],
    },

    //aca pueden agregar mas categorias

  ],
};

export default sidebars;
