name: CI/CD Documentation Crudzaso

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.1.0
        env:
          PATH: ${{ secrets.PATH }}
          NAME_SERVICE: ${{ secrets.NAME_SERVICE}}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          envs: PATH,NAME_SERVICE
          script: |
            cd $PATH
            git pull origin main
            pm2 restart $NAME_SERVICE
