name: CI/CD Documentation Crudzaso

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure bash is installed
        run: sudo apt-get install -y bash
   
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.6
        env:
          PATH: ${{ secrets.PATH }}
          NAME_SERVICE: ${{ secrets.NAME_SERVICE}}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: PATH,NAME_SERVICE
          script: |
            cd $PATH
            git pull origin main
            pm2 restart $NAME_SERVICE
